name: test
on: [push]

jobs:
  build:
    strategy:
      matrix:
        nim-version: ['stable', 'devel']

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - run: nimble c socketcan.nim
